### ISSUE TITLE
BIC definition incorrect

### ISSUE THREAD

**Issue by lukauskas** [nsgrantham/nsgrantham.github.io#1]
In your review on Bernoulli Mixture Models (which I think is great, by the way!), section 4.2.1, you say that psi = log N results in a BIC penalised likelihood.

This would, however result in BIC = -2L + 2 log(N) eta , whereas it is more commonly defined as BIC = -2L + log(N) eta (i.e. see [wiki](https://en.wikipedia.org/wiki/Bayesian_information_criterion)). 

Therefore either psi should be 1/2 * log N or the previous equation should not multiply by two (and then psi=2 for AIC).

**Comment by nsgrantham** [comment]
Ah, you are right, good eye! Glad to hear you found the review helpful.
